//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revolt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RevoltEntities : DbContext
    {
        public RevoltEntities()
            : base("name=RevoltEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Revoltist> Revoltists { get; set; }
        public virtual DbSet<RevoltistGameScore> RevoltistGameScores { get; set; }
        public virtual DbSet<RevoltistTitle> RevoltistTitles { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
    }
}
