//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revolt
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevoltistTitle
    {
        public int id { get; set; }
        public long title { get; set; }
    
        public virtual Revoltist Revoltist { get; set; }
    }
}
