//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revolt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public long titleId { get; set; }
        public string title1 { get; set; }
    }
}
